### PR TITLE
6 scraping lecturers schedules

### LINKED ISSUE #6: Scraping lecturers' schedules

### PR DESCRIPTION
**Pull request by grzegorzbogusz**
Closes #6

### CODE REVIEW

**Comment by Anna-Sokolowska** [comment]
There are no conditions for empty queries results

**Comment by Anna-Sokolowska** [comment]
Schedule is created only with Lecturer. If Schedule is deleted it will never create again.

**Review by Anna-Sokolowska — COMMENTED** [review]
There are no conditions for empty queries results

**Review by Anna-Sokolowska — COMMENTED** [review]
Schedule is created only with Lecturer. If Schedule is deleted it will never create again.

**Comment by grzegorzbogusz** [comment]
Added changes respecting recent code review

**Review by Anna-Sokolowska — APPROVED** [review]

**Review by Anna-Sokolowska — APPROVED** [review]

**Pull request merged**
